### ISSUE TITLE
some error not able to get it

### ISSUE THREAD

**Issue by animeshsingh04** [pawanaichra/stock-movement-prediction-using-hmm-in-python#1]
price_movement = get_price_movements(stock_prices)
    optimal_states = hmm.get_optimal_states(price_movement)

error for above two line of code
Traceback (most recent call last):
  File "C:/Users/ANIMESH/Desktop/stock-movement-prediction-using-hmm-in-python-master/stock-movement-prediction-using-hmm-in-python-master/stock-prediction.py", line 151, in <module>
    price_movement = get_price_movements(stock_prices)
  File "C:/Users/ANIMESH/Desktop/stock-movement-prediction-using-hmm-in-python-master/stock-movement-prediction-using-hmm-in-python-master/stock-prediction.py", line 142, in get_price_movements
    price_movement = int(np.array(list(map((lambda x: 1 if x >0 else 0, price_change)))))
TypeError: map() must have at least two arguments.

**Comment by pawanaichra** [comment]
I think its due to version problem. Its working fine with 3.6 and maybe now will also work with other versions.

**Comment by animeshsingh04** [comment]
Even I hv same 3.6 version

**Comment by animeshsingh04** [comment]
![image](https://user-images.githubusercontent.com/32563403/39464526-96606eb4-4d3b-11e8-86a2-6d92f95be874.png)
please check this

**Comment by pawanaichra** [comment]
well, this may be problem with your compiler. Check it out on google. It was tested on Anaconda python 3.6
![capture](https://user-images.githubusercontent.com/14900576/39467625-95b9e254-4d4c-11e8-9443-298f766ace68.PNG)
